version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Echo Hello World
          command: echo "Hello, World!"
workflows:
  version: 2
  build:
    jobs:
      - build
